[main]
    separator = "-"
    description = "Runtime Verification Conference 2024"
    enableDarkMode = true
    modes = ["light", "dark"]
    canonifyAssetsURLs = false
    endorse = true
    footerBelowFold = false
    loading = "lazy"
    breakpoint = "md"
    [main.externalLinks]
        cue = false
        tab = false
    [main.build]
        transpiler = "libsass"

[modules]
    core = ["bootstrap", "flexsearch", "fontawesome"]
    optional = ["leaflet", "katex", "lottie"]
    excludeSCSS = ["bootstrap"]
    disableTemplate = ["katex"]
    [modules.katex]
        state = "defer"
    [modules.fontawesome]
        inline = true
        debug = true
        skipMissing = false

[debugging]
    showJS = false
    showSCSS = false
    purgeHTMLComments = false

[home]
    fullCover = false
    centerHeadline = true
    style = ""
    sections = ["summary", "papers", "sponsors"]
    [home.feature]
        orientation = "horizontal"
        color = "primary"
        width = 4
        align = "start"

[navigation]
    anchor = true
    logo = "/img/rv24_logo.svg"
    color = "body"
    fixed = true
    offset = "5.5rem"
    search = true
    searchModal = false
    breadcrumb = true
    toc = true
    sidebar = true
    size = "md"

[messages]
    placement = "bottom-right"

[sections]
    [sections.summary]
        title = "Welcome to Runtime Verification 2024"
        layout = "list"
        sort = "weight"
        homepage = 3
        header = "none"
        footer = "none"
        style = "px-0"    
    [sections.papers]
        header = "none"
        footer = "none"
    [sections.sponsors]
        title = "Sponsors"
        sectionHeader = "justify-content-end"
        layout = "card"
        sort = "weight"
        reverse = false
        background = ""
        style = "border-0 card-feature"
        cols = 4
        padding = "3"
        header = "none"
        footer = "none"
        orientation = "stacked"
        homepage = 12
    [sections.venue]
        header = "none"
        footer = "none"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 10

[[sharing.providers]]
    name = "Twitter"
    url = "https://twitter.com/home?status={url}"
    icon = "fab x-twitter"
    weight = 20

[[sharing.providers]]
    name = "Facebook"
    url = "https://www.facebook.com/sharer.php?u={url}"
    icon = "fab facebook"
    weight = 30

[[sharing.providers]]
    name = "email"
    url = "{url}"
    icon = "fas link"
    weight = 50
    clipboard = true

# toml-docs-start sections
# [sections]
#     [sections.posts]
#         title = "Posts"
#         sort = "date"
#         reverse = true
#         nested = true
#         cols = 3
#         color = ""
#         padding = "0"
#         header = "full"
#         footer = "none"
#         orientation = "stacked"
#         style = "border-0 card-zoom"
#         homepage = 3
#         separator = true
# toml-docs-end sections

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]

[style]
    primary = "#581845" # "#d43900"
    secondary = "#6c757d"
    success = "#198754"
    info = "#0dcaf0"
    warning = "#ffc107"
    danger = "#dc3545"
    light = "#f8f9fa"
    dark = "#212529"
    themeOpacity = "10"
    darkModeShade = "20%"
    darkModeTint = "40%"
    themeFont = "Inter"
    # themeFontPath = "https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" # external path
    themeFontPath = "/fonts" # local path
    fontSizeBase = "1rem"
    purge = false

[schema]
    type = "Organization"
    name = "Hinode"
    locale = "en-US"
    # twitter = "https://twitter.com/gethinode"
    # linkedIn = ""
    github = "https://github.com/bouncmpe/rv24"
    section = "blog"
    [author]
        name = "Dogan Ulus"
        # twitter = "https://twitter.com/markdumay"
        linkedin = "https://www.linkedin.com/in/doganulus/"
        github = "https://github.com/doganulus"
    [logo]
        url = "img/logo512x512.png"
        width = 512
        height = 512
    [image]
        url = "img/logo1280x640.png"
        width = 1280
        height = 640

[opengraph]
    images = ["logo.png"]
    locale = "en_US"

