[[main]]
  name = "Home"
  pageRef = ""
  weight = 1

[[main]]
  name = "Call for Papers"
  pageRef = "call-for-papers"
  weight = 10

[[main]]
  name = "Committees"
  pageRef = "committees"
  weight = 30

[[main]]
  name = "Keynotes"
  pageRef = "keynotes"
  weight = 30

[[main]]
  name = "Program"
  pageRef = "program"
  weight = 40

[[main]]
  name = "Awards"
  pageRef = "awards"
  weight = 50

[[main]]
  name = "Venue"
  pageRef = "venue"
  weight = 60

[[main]]
  name = "Registration"
  pageRef = "registration"
  weight = 100

# [[social]]
#   name = "Twitter"
#   pre = "fab x-twitter"
#   url = "https://twitter.com/runverif"
#   weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/runtime-verification"
  weight = 20
